site_name: Jaemin Oh

site_url: https://jaeminoh.github.io
repo_url: https://github.com/jaeminoh/jaeminoh.github.io

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - blog
  - bibtex:
      bib_file: "bibliography/library.bib"
      csl_file: "bibliography/ima.csl"

markdown_extensions:
  - md_in_html
  - def_list
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra:
  analytics:
    provider: google
    property: G-B9XBB4QRXM

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js