site_name: Jaemin Oh

theme:
  name: material

plugins:
  - search
  - blog

markdown_extensions:
  - def_list
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra:
  analytics:
    provider: google
    property: G-B9XBB4QRXM

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js